import SectionWrapper from "./SectionWrapper";
import styles from "./Projects.module.css";

const PROJECTS = [
  {
    title: "Tratto",
    desc: "Neuro-symbolic framework for generating axiomatic test oracles from Java method documentation.",
    url: "https://github.com/darthdaver",
  },
  {
    title: "Oracle LLM Study",
    desc: "Empirical study evaluating the quality of test oracles generated by large language models.",
    url: "https://github.com/darthdaver",
  },
  {
    title: "Smart Ecosystem Health",
    desc: "Failure prediction and health monitoring for smart human-centric ecosystems.",
    url: "https://github.com/darthdaver",
  },
];

export default function Projects() {
  return (
    <SectionWrapper id="projects" index="04" title="Projects">
      <div className={styles.grid}>
        {PROJECTS.map(({ title, desc, url }) => (
          <a
            key={title}
            href={url}
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h3 className={styles.cardTitle}>{title}</h3>
            <p className={styles.cardDesc}>{desc}</p>
            <span className={styles.cardLink}>View repository →</span>
          </a>
        ))}
      </div>
    </SectionWrapper>
  );
}
